# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rn3TaUKBtBwi_dhHWrbkbzfDwiCRnu8H
"""

# ============================================================
# COTIZADOR + PROYECCIÓN — versión web (Streamlit)
# Adaptación completa de notebook original (2025)
# Diseño negro/naranja (#F87B1B)
# ============================================================

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import uuid

# ---------------------------------------
# CONFIGURACIÓN VISUAL
# ---------------------------------------
st.set_page_config(page_title="Cotizador de Remodelación", layout="wide")

st.markdown("""
    <style>
    body {background-color: #0E0E0E; color: white;}
    .stApp {background-color: #0E0E0E;}
    h1, h2, h3, h4, h5, h6 {color: #F87B1B;}
    .stButton>button {
        background-color: #F87B1B;
        color: white;
        border: none;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        font-weight: 600;
    }
    .stButton>button:hover {background-color: #ff912e;}
    .stSelectbox, .stTextInput, .stNumberInput, .stRadio, .stCheckbox, .stSlider {
        color: white !important;
    }
    </style>
""", unsafe_allow_html=True)

# ---------------------------------------
# CATÁLOGOS
# ---------------------------------------
CATALOGO_BLANCA = {
    "Pisos y Revestimientos": {
        "Piso cerámica estándar": 80000,
        "Piso porcelanato nacional": 140000,
        "Piso laminado": 110000,
        "Piso mármol": 300000,
    },
    "Paredes y Pintura": {
        "Pintura vinílica": 25000,
        "Papel tapiz decorativo": 60000,
    },
    "Carpintería y Puertas": {
        "Puerta MDF estándar": 380000,
        "Puerta madera maciza": 750000,
    },
}

CATALOGO_NEGRA = {
    "Partidas de Obra Negra": {
        "Demolición controlada (m²)": 50000,
        "Cimentación corridas (m³)": 320000,
        "Estructura de concreto (m³)": 450000,
        "Mampostería/muros (m²)": 120000,
    }
}

MULT_COLOR   = {"Blanco/Neutro":1.00, "Gris/Beige":1.05, "Negro/Especial":1.10}
MULT_ACABADO = {"Mate/Liso":1.00, "Brillante/Pulido":1.10, "Texturizado":1.12}
MULT_ORIGEN  = {"Nacional":1.00, "Importado":1.15}
LEVEL_MULT   = {"Básico": 0.90, "Estándar": 1.00, "Premium": 1.40}
INTEL_PLUS   = 0.15
IVA = 0.19

# ---------------------------------------
# FUNCIONES
# ---------------------------------------
def form_cop(v): return f"COP ${v:,.0f}"

def calcular_total(items, mano_pct, imp_pct):
    subtotal = sum(i['subtotal'] for i in items)
    mano_obra = subtotal * mano_pct / 100
    imprev = (subtotal + mano_obra) * imp_pct / 100
    iva_val = (subtotal + mano_obra + imprev) * IVA
    total = subtotal + mano_obra + imprev + iva_val
    return subtotal, mano_obra, imprev, iva_val, total

# ---------------------------------------
# UI PRINCIPAL
# ---------------------------------------
st.title("🏗️ Cotizador de Remodelación")

obra_tipo = st.radio("Selecciona el tipo de obra:", ["Obra blanca (acabados/interiores)", "Obra negra (estructura/obra gris)"])
if obra_tipo.startswith("Obra blanca"):
    CATALOGO = CATALOGO_BLANCA
    mano_pct, imp_pct = 15.0, 10.0
else:
    CATALOGO = CATALOGO_NEGRA
    mano_pct, imp_pct = 18.0, 12.0

st.divider()
st.subheader("1️⃣ Agregar ítems a la cotización")

if 'items' not in st.session_state:
    st.session_state.items = []

col1, col2 = st.columns(2)
categoria = col1.selectbox("Categoría", list(CATALOGO.keys()))
material = col2.selectbox("Ítem/partida", list(CATALOGO[categoria].keys()))
cantidad = st.number_input("Cantidad", min_value=0.0, value=10.0, step=1.0)

nivel = st.radio("Nivel de acabado", list(LEVEL_MULT.keys()), horizontal=True)
origen = st.radio("Origen del material", list(MULT_ORIGEN.keys()), horizontal=True)

mult = LEVEL_MULT[nivel] * MULT_ORIGEN[origen]
if obra_tipo.startswith("Obra blanca"):
    color = st.selectbox("Color", list(MULT_COLOR.keys()))
    acabado = st.selectbox("Acabado", list(MULT_ACABADO.keys()))
    inteligente = st.checkbox("Opción Inteligente (+15%)")
    mult *= MULT_COLOR[color] * MULT_ACABADO[acabado]
    if inteligente:
        mult *= (1 + INTEL_PLUS)
else:
    color = acabado = None
    inteligente = False

precio_unit = CATALOGO[categoria][material]
subtotal = precio_unit * cantidad * mult

st.write(f"💰 **Subtotal estimado:** {form_cop(subtotal)}")

if st.button("➕ Agregar ítem"):
    item = {
        "id": str(uuid.uuid4())[:8],
        "categoria": categoria,
        "material": material,
        "cantidad": cantidad,
        "precio_base": precio_unit,
        "nivel": nivel,
        "origen": origen,
        "subtotal": subtotal,
        "color": color,
        "acabado": acabado,
        "inteligente": inteligente,
    }
    st.session_state.items.append(item)
    st.success("Ítem agregado correctamente ✅")

if st.button("🗑️ Vaciar lista"):
    st.session_state.items.clear()

# ---------------------------------------
# TABLA Y RESUMEN
# ---------------------------------------
if st.session_state.items:
    df = pd.DataFrame(st.session_state.items)
    df_show = df.copy()
    df_show["precio_base"] = df_show["precio_base"].map(form_cop)
    df_show["subtotal"] = df_show["subtotal"].map(form_cop)
    st.dataframe(df_show, use_container_width=True)

    subtotal, mano_obra, imprev, iva_val, total = calcular_total(st.session_state.items, mano_pct, imp_pct)
    st.markdown(f"""
    ### 🧾 Totales
    - Subtotal: **{form_cop(subtotal)}**
    - Mano de obra ({mano_pct:.0f}%): **{form_cop(mano_obra)}**
    - Imprevistos ({imp_pct:.0f}%): **{form_cop(imprev)}**
    - IVA (19%): **{form_cop(iva_val)}**
    - 💵 **Total estimado:** {form_cop(total)}
    """)

    # Pie chart
    by_cat = df.groupby("categoria")["subtotal"].sum()
    fig, ax = plt.subplots()
    ax.pie(by_cat.values, labels=by_cat.index, autopct='%1.1f%%', startangle=140)
    ax.set_title("Distribución de costos por categoría")
    st.pyplot(fig)

else:
    st.info("Agrega ítems para ver el resumen y la proyección.")

# ---------------------------------------
# PROYECCIÓN DE COSTOS
# ---------------------------------------
st.divider()
st.subheader("📈 Proyección de Costos")

escenario = st.selectbox("Escenario de proyección", ["Peor de los casos", "Escenario normal", "Mejor de los casos"])
meses = st.slider("Meses de proyección", 0, 36, 6)

ESCENARIOS = {
    "Peor de los casos": (0.10, 0.08, 0.10),
    "Escenario normal":  (0.06, 0.06, 0.05),
    "Mejor de los casos":(0.03, 0.03, 0.00),
}
g_mat, g_lab, g_fx = ESCENARIOS[escenario]
t = meses / 12.0

if st.session_state.items:
    df = pd.DataFrame(st.session_state.items)
    df['proj'] = df.apply(lambda r: r['precio_base'] * (1 + g_mat*t) * (1 + g_fx*t if r['origen']=="Importado" else 1) * r['cantidad'] * LEVEL_MULT[r['nivel']], axis=1)
    total_proj = df['proj'].sum()
    st.write(f"📊 **Total proyectado a {meses} meses ({escenario}): {form_cop(total_proj)}**")

    # Evolución
    meses_list = list(range(meses + 1))
    totales = []
    for m in meses_list:
        tm = m / 12.0
        df['temp'] = df.apply(lambda r: r['precio_base'] * (1 + g_mat*tm) * (1 + g_fx*tm if r['origen']=="Importado" else 1) * r['cantidad'] * LEVEL_MULT[r['nivel']], axis=1)
        totales.append(df['temp'].sum())

    fig2, ax2 = plt.subplots()
    ax2.plot(meses_list, totales, marker='o', color='#F87B1B')
    ax2.set_title("Evolución del costo proyectado")
    ax2.set_xlabel("Meses")
    ax2.set_ylabel("Total proyectado (COP)")
    ax2.grid(True, alpha=0.3)
    st.pyplot(fig2)